# Generated by Django 5.2.15 on 2026-06-12 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('cni', models.CharField(max_length=50, unique=True, verbose_name='CNI')),
                ('numero_permis', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livreurs/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('en_service', 'En service'), ('maintenance', 'Maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('adresse_depart', models.CharField(max_length=255)),
                ('adresse_destination', models.CharField(max_length=255)),
                ('latitude_destination', models.FloatField(blank=True, null=True)),
                ('longitude_destination', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee')], default='planifiee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='parc.livreur')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='parc.moto')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('non_lue', 'Non lue'), ('lue', 'Lue'), ('traitee', 'Traitee')], default='non_lue', max_length=20)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='parc.mission')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='parc.moto')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='parc.livreur')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='parc.moto')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PreuveLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_receptionnaire', models.CharField(max_length=150)),
                ('signature', models.TextField()),
                ('latitude_validation', models.FloatField(blank=True, null=True)),
                ('longitude_validation', models.FloatField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(default=django.utils.timezone.now)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preuve', to='parc.mission')),
            ],
            options={
                'ordering': ['-date_validation'],
            },
        ),
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vitesse', models.FloatField(default=0)),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='parc.moto')),
            ],
            options={
                'ordering': ['-date_heure'],
                'indexes': [models.Index(fields=['moto', '-date_heure'], name='parc_positi_moto_id_a57bbf_idx')],
            },
        ),
    ]
